name: "Build and deploy"

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      id:
        required: true
        type: string

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    outputs:
      cdn_url: ${{ steps.extract-manifest-url.outputs.url }}
      image: ${{ steps.docker-build-push.outputs.image }}

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
          cache: npm
      - name: Install dependencies
        run: npm ci
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Cypress tests
        run: npx cypress run --component
      - name: Build application
        run: npm run build

      - name: cdn-upload
        id: cdn-upload
        uses: nais/deploy/actions/cdn-upload/v2@master
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          team: team-esyfo
          source: ./dist/
          destination: ${{ inputs.app }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

      - name: Extract manifest url
        id: extract-manifest-url
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: |
          files="${{ steps.cdn-upload.outputs.uploaded }}"
          first_file=$(echo $files | cut -d',' -f1)
          echo "url=https://cdn.nav.no/$first_file" >> $GITHUB_OUTPUT

      - name: Build and push docker image
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: team-esyfo
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  update-manifest-dev:
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: build
    uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest-v2.yaml@main
    with:
      cluster: dev-gcp
      id: ${{ inputs.id }}
      url: ${{needs.build.outputs.cdn_url}}
    secrets: inherit

  update-manifest-prod:
    if: github.ref == 'refs/heads/main'
    needs: build
    uses: navikt/tms-deploy/.github/workflows/oppdater-mikrofrontend-manifest-v2.yaml@main
    with:
      cluster: prod-gcp
      id: ${{ inputs.id }}
      url: ${{needs.build.outputs.cdn_url}}
    secrets: inherit
